Ext.define("app.view.vue.vuebut.VueBut",{
    extend:"Ext.window.Window",
    alias:"view.vueBut",
    requires:[
        "Fm.ux.Ueditor",
        "app.view.vue.vuebut.VueButController",
        "app.view.vue.vuebut.VueButModel"
    ],
    controller:'vueButController',
    viewModel: {
        type: 'vueButModel'
    },
    layout:{
        type:"table",
        columns:1,
    },
    selValue:null,
    scrollable:"y",
    defaults:{
        width:440,
        labelWidth:60,
        labelAlign:'right'
    },
    width:500,
    height:400,
    items:[
        {
            xtype:"fieldcontainer",
            layout:{
                type:"table",
                columns:2
            },
            defaults:{
                labelWidth:60,
                labelAlign:"right",
                width:220
            },
            items:[ 
                {
                xtype:"textfield",
                fieldLabel:"功能",
                bind:"{vueCom.title}",
            },{
                xtype:"numberfield",
                fieldLabel:"顺序",
                bind:"{vueCom.sort}",
                minValue:0
            }]
            
        },{
            xtype:"fieldcontainer",
            layout:{
                type:"table",
                column:2
            },
            items:[
                {
                    xtype:"displayfield",
                    fieldLabel:"功能描述",
                    labelAlign:'right',
                    labelWidth:60
                },{xtype:"ueditor",
                    itemId:"comDes",
                    height:100,
                    width:378,
                    ueditorConfig:{
                        toolbars:[],
                        pasteplain:true
                    }
            }
            ]
            
        },
        {
            xtype:"textfield",
            fieldLabel:"示例按钮",
            bind:"{vueCom.but}"
        },{
            xtype:"fieldcontainer",
            layout:{
                type:"table",
                columns:2
            },
            items:[
                {
                    xtype:"displayfield",
                    fieldLabel:"示例代码",
                    labelWidth:60,
                    labelAlign:"right"
                },{
                    xtype:"ueditor",
                    width:378,
                    height:200,
                    bind:{
                        value:"{vueCom.code}"
                    }
                }
            ]
        }
    ],
    initComponent:function(){
        var me=this;
        me.bbar=[
            "->",
            {
                xtype:"button",
                text:"确定" ,
                handler:"ok"
            },{
                xtype:'button',
                text:"取消",
                handler:function(){
                    this.close();
                },
                scope:this
            }
        ]
        me.callParent(arguments);
    }
})